config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :sessions, only: [:create, :destroy]
  get 'users/sign_in', to: 'sessions#new'
  get 'users/sign_up', to: 'users#new'
  post 'users', to: 'users#create'
  get 'users/histories'
  root "histories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true
  has_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def authenticated_user!
    redirect_to users_sign_in_path, alert: 'Necesitas abrir la sesión para revisar esa sección' unless helpers.logged?
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  before_action :authenticated_user!, except: [:index]
  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)
    @history.user = helpers.current_user

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'Storie ha sido creado.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'Storie ha sido actualizado.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'Storie ha sido borrado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:title, :picture, :content, :remote_picture_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user.nil?
      redirect_to users_sign_in_path, alert: 'El correo no está asociado'
      return
    end
    if @user.password == params[:user][:password]
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to users_sign_in_path, alert: 'Password incorrecto'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
   if @user.save
    session[:user_id] = @user.user_id
    redirect_to root_path
    else
      render :new, notice: 'Not found user'
    end
  end
  

  def histories
    @histories = helpers.current_user.histories
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def logged?
    session[:user_id].present?
  end

  def current_user
    User.find(session[:user_id])
  end
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true, multipart: true, class: "form-horizontal") do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <%= form.label :title, "Título", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_field :title, id: :history_title, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :remote_picture_url, "URL Imagen", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= image_tag(history.picture.thumb, style: "margin-bottom: 10px; border-radius: 5px;") if history.picture? %>

        <%= form.text_field :remote_picture_url, id: :history_picture, class: "form-control" %>
      </div>
      <%= form.hidden_field :picture_cache %>
    </div>

    <div class="form-group">
      <%= form.label :content, "Descripción", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_area :content, id: :history_content, class: "form-control", rows: 10 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= form.submit "Enviar", class: "btn btn-primary" %>
        <%= link_to 'Back', histories_path, class: "btn btn-default"  %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/histories/edit.html.erb
<legend>Editar Historia</legend>

<%= render 'form', history: @history %>

app/views/histories/index.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>Histories</h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-2">
    <%= link_to 'New History', new_history_path, class: "btn btn-info btn-sm" %>
  </div>
</div>

<div class="row">
  <% @histories.reverse.each do |history| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(history.picture.thumb), history) if history.picture? %>
        <div class="caption">
          <h3><%= history.title %></h3>
          <small><%= time_ago_in_words(history.created_at) %> ago</small>
          <p><%= history.content.truncate(150)  %></p>
          <p>
            <%= link_to 'Show', history, class: "btn btn-primary" %>
            <%= link_to 'Edit', edit_history_path(history), class: "btn btn-warning" %>
            <%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

app/views/histories/new.html.erb
<legend>Nueva Historia</legend>

<%= render 'form', history: @history %>

app/views/histories/show.html.erb
<div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <%= image_tag(@history.picture_url, style: "max-width: 100%; border-radius: 10px;") if @history.picture? %>
        </div>
        <div class="col-md-2"></div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h1><%= @history.title %></h1>
          <small><%= time_ago_in_words(@history.created_at) %> ago</small>
        </div>
        <div class="col-md-2"></div>
      </div>

      <hr>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <p><%= @history.content %></p>
        </div>
        <div class="col-md-2"></div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-2">
          <p><%= link_to 'Edit', edit_history_path(@history), class: "btn btn-warning btn-sm" %> <%= link_to 'Back', histories_path, class: "btn btn-info btn-sm" %></p>
        </div>
        <div class="col-md-2"></div>
      </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictory</title>
    <%= csrf_meta_tags %>

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/3.4.1/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-6SQbkR6/v7QGEoFg1os3KF4uJMFxP6vxm6vLCSbbwwHllJdb4FqkWMiYLtHWGGN4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <% if notice %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Información</h4>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Atención</h4>
          <p><%= alert %></p>
        </div>
      <% end %>      
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Pictory</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/histories/1">Stories 1</a></li>
        <li><a href="/histories/2">Stories 2</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <% if logged? %>
              Bienvenido <%= current_user.name  %>
            <% else %>
              Log in
            <% end %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% if logged? %>
              <li><%= link_to 'My Stories', users_histories_path %></li>
              <li><%= link_to 'Log out', session_path(current_user), method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign up', users_sign_up_path %></li>
              <li><%= link_to 'Log in', users_sign_in_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/histories.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>Stories de <%= current_user.name %></h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-2">
    <%= link_to 'New History', new_history_path, class: "btn btn-info btn-sm" %>
  </div>
</div>

<div class="row">
  <% @histories.each do |history| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(history.picture.thumb), history) if history.picture? %>
        <div class="caption">
          <h3><%= history.title %></h3>
          <small><%= time_ago_in_words(history.created_at) %> ago</small>
          <p><%= history.content.truncate(150)  %></p>
          <p>
            <%= link_to 'Show', history, class: "btn btn-primary" %>
            <%= link_to 'Edit', edit_history_path(history), class: "btn btn-warning" %>
            <%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true, multipart: true, class: "form-horizontal") do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this User from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <%= form.label :name, "Name", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :email, "Email", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_field :email, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :password, "Password", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.password_field :password, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= form.submit "Sign up", class: "btn btn-primary" %>
        <%= link_to 'Back', root_path, class: "btn btn-default"  %>
      </div>
    </div>
  </fieldset>
<% end %>